// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSdCmQ8z8a9VgBnPSXXzttsMAqHuwwRm8',
    appId: '1:356368004720:web:1734471fd43f021e7c26b5',
    messagingSenderId: '356368004720',
    projectId: 'mini-project-56c4e',
    authDomain: 'mini-project-56c4e.firebaseapp.com',
    storageBucket: 'mini-project-56c4e.firebasestorage.app',
    measurementId: 'G-PXXM0LKK10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKfsp0adEMgtFKN3WHFftAgPWN3jUKiI',
    appId: '1:356368004720:android:ed68cf4571ce23817c26b5',
    messagingSenderId: '356368004720',
    projectId: 'mini-project-56c4e',
    storageBucket: 'mini-project-56c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzM9PHQABgAAORRId91FNMVCWAS_EH1k4',
    appId: '1:356368004720:ios:ae9b7d304b0377be7c26b5',
    messagingSenderId: '356368004720',
    projectId: 'mini-project-56c4e',
    storageBucket: 'mini-project-56c4e.firebasestorage.app',
    iosBundleId: 'com.example.myMiniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzM9PHQABgAAORRId91FNMVCWAS_EH1k4',
    appId: '1:356368004720:ios:ae9b7d304b0377be7c26b5',
    messagingSenderId: '356368004720',
    projectId: 'mini-project-56c4e',
    storageBucket: 'mini-project-56c4e.firebasestorage.app',
    iosBundleId: 'com.example.myMiniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSdCmQ8z8a9VgBnPSXXzttsMAqHuwwRm8',
    appId: '1:356368004720:web:7eed41df4b884a5c7c26b5',
    messagingSenderId: '356368004720',
    projectId: 'mini-project-56c4e',
    authDomain: 'mini-project-56c4e.firebaseapp.com',
    storageBucket: 'mini-project-56c4e.firebasestorage.app',
    measurementId: 'G-F12RBXFSG1',
  );
}
