// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzz1qq1eNsDlWrqtCa6THIdUYR_oik4Yo',
    appId: '1:301777078214:web:c0a59389b21b9581a294c7',
    messagingSenderId: '301777078214',
    projectId: 'flutter-notes-app-8dcdf',
    authDomain: 'flutter-notes-app-8dcdf.firebaseapp.com',
    storageBucket: 'flutter-notes-app-8dcdf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81hzmrnD--T6CiZG4qAVb5n2-YrbeQe0',
    appId: '1:301777078214:android:8573abf716089ba6a294c7',
    messagingSenderId: '301777078214',
    projectId: 'flutter-notes-app-8dcdf',
    storageBucket: 'flutter-notes-app-8dcdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANtxFfZQAPNttttqqPWR1-TU5sS1EJWuY',
    appId: '1:301777078214:ios:6e243939ad32d823a294c7',
    messagingSenderId: '301777078214',
    projectId: 'flutter-notes-app-8dcdf',
    storageBucket: 'flutter-notes-app-8dcdf.firebasestorage.app',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANtxFfZQAPNttttqqPWR1-TU5sS1EJWuY',
    appId: '1:301777078214:ios:6e243939ad32d823a294c7',
    messagingSenderId: '301777078214',
    projectId: 'flutter-notes-app-8dcdf',
    storageBucket: 'flutter-notes-app-8dcdf.firebasestorage.app',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzz1qq1eNsDlWrqtCa6THIdUYR_oik4Yo',
    appId: '1:301777078214:web:011ebcba18e834b8a294c7',
    messagingSenderId: '301777078214',
    projectId: 'flutter-notes-app-8dcdf',
    authDomain: 'flutter-notes-app-8dcdf.firebaseapp.com',
    storageBucket: 'flutter-notes-app-8dcdf.firebasestorage.app',
  );
}
